// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokTable, StoryblokMultilink } from '../storyblok.d.ts';
export interface Page {
  body?: (Page | Profile | Project | Social)[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface Profile {
  title?: string;
  biography?: StoryblokTable;
  photoUrl?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "Profile";
  _uid: string;
  [k: string]: unknown;
}

export interface Project {
  Project?: StoryblokTable;
  component: "Project";
  _uid: string;
  [k: string]: unknown;
}

export interface Social {
  socialLinks?: StoryblokTable;
  component: "Social";
  _uid: string;
  [k: string]: unknown;
}
