// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokTable, StoryblokMultilink } from '../storyblok.d.ts';
export interface Client {
  clients?: StoryblokTable;
  component: "Client";
  _uid: string;
  [k: string]: unknown;
}

export interface Connect {
  connect?: StoryblokTable;
  component: "Connect";
  _uid: string;
  [k: string]: unknown;
}

export interface Menu {
  menu?: StoryblokTable;
  component: "Menu";
  _uid: string;
  [k: string]: unknown;
}

export interface Meta {
  title?: string;
  description?: string;
  favicon?: string;
  component: "meta";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (Client | Connect | Menu | Meta | Page | Profile | Project | Service | Social | TechStack)[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface Profile {
  title?: string;
  biography?: StoryblokTable;
  photoUrl?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "Profile";
  _uid: string;
  [k: string]: unknown;
}

export interface Project {
  Project?: StoryblokTable;
  component: "Project";
  _uid: string;
  [k: string]: unknown;
}

export interface Service {
  bookCallLink?: string;
  emailLink?: string;
  services?: StoryblokTable;
  component: "Service";
  _uid: string;
  [k: string]: unknown;
}

export interface Social {
  socialLinks?: StoryblokTable;
  component: "Social";
  _uid: string;
  [k: string]: unknown;
}

export interface TechStack {
  tech_stack?: StoryblokTable;
  component: "Tech Stack";
  _uid: string;
  [k: string]: unknown;
}
